
CREATE TABLE PRODUTOS
(CODPRODUTO INT,
NOMEPRODUTO VARCHAR(20),
PRECOPRODUTO MONEY,
QUANTIDADE SMALLINT,
TOTAL AS (PRECOPRODUTO*QUANTIDADE)
)

select * from produtos

INSERT INTO produtos (CODPRODUTO, NOMEPRODUTO, PRECOPRODUTO, QUANTIDADE)
VALUES (1,'PICANHA',80.00,2),
(2,'ALCATRA',40.00,5),
(3,'MAMINHA',60.00,7),
(4,'COXÃO DURO',30.00,8),
(5,'CONTRA FILÉ',50.00,80),
(6,'CAFTA',20.00,20),
(7,'CABEÇA',15.00,5),
(8,'TRIPA',25.00,1)


INSERT INTO PRODUTOS VALUES (9,'FILÉ MIGNON',62.00,2)
INSERT INTO PRODUTOS VALUES (10,'FILÉ DE FRANGO',14.00,6)

UPDATE PRODUTOS SET PRECOPRODUTO=30.00 WHERE CODPRODUTO=9

select * from PRODUTOS WHERE CODPRODUTO=9

SELECT SUM(TOTAL) FROM PRODUTOS

CREATE TABLE TAB_FORNECEDOR
(CODIGO INT,
FORNECEDOR NVARCHAR(100),
SERVICOS VARCHAR(50),
VALOR_SERV DECIMAL(12,2),
ISS AS VALOR_SERV * 0.05,
VALOR_LIQ AS VALOR_SERV-(VALOR_SERV * 0.05),
DATA_INSCRICAO AS GETDATE()
)

SELECT NOMEPRODUTO,(PRECOPRODUTO -5) AS PRECOCOMDESCONTO FROM PRODUTOS

SELECT NOMEPRODUTO,(PRECOPRODUTO *2) AS PRECOX2 FROM PRODUTOS


SELECT NOMEPRODUTO,(PRECOPRODUTO /2) AS PRECO50_OFF FROM PRODUTOS