
--LAURA XAVIER CHAGAS 2DSV


USE [BDCADASTRO]
GO

/****** Object:  View [dbo].[VW_CLIENTE]    Script Date: 09/09/2022 16:28:02 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


ALTER VIEW [dbo].[VW_CLIENTE] AS
	SELECT IDCLIENTE, NOME, IDADE FROM CLIENTE
	WHERE IDCLIENTE <>0
GO


	DROP VIEW VW_CLIENTE