SELECT * FROM CLIENTE
SELECT * FROM COMPRA
SELECT * FROM PRODUTO

SELECT CL.LAURA AS NOMES_DOS_CLIENTES,
PR.NOMEDOPRODUTO, CO.QUANTIDADE, PR.PREÇO * CO.QUANTIDADE
AS TOTAL
FROM 'CLIENTE' AS CL
INNER JOIN COMPRA AS CO
ON CL.IDCLIENTE = CO.CODCOMPRA
INNER JOIN PRODUTO AS PR
ON CO.CODPRODUTO

GROUP BY CL.NOMECLIENTE

SELECT (SELECT'LAURA') AS NOMEDASUBCONSULTA

SELECT RESULTADO.NOMES_DOS_CLIENTES, SUM (RESULTADO.TOTAL) S TOTAL
FROM (SELECT CL.NOMECLIENTE AS NOMES_DOS_CLIENTES, PR.PREÇO * CO.QUANTIDADE
AS TOTAL 
FROM CLIENTE AS CL
INNER JOIN COMPRA AS CO 
ON CL.IDCLIENTE = CO.CODCOMPRA
INNER JOIN PRODUTO AS PR
ON CO.ID = PR.ID
) AS RESULTADO
GROUP BY RESULTADO.NOMES_DOS_CLIENTES
ORDER BY TOTAL